name: Security Scans

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install Trivy
      #   run: |
      #     curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # - name: Run Trivy Scan
      #   run: |
      #     trivy fs . --exit-code 1 --severity HIGH,CRITICAL

      # Install TFLint
      # - name: Install TFLint
      #   run: |
      #     curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Use tflint from Marketplace
      - name: Setup TFLint from Marketplace
        uses: terraform-linters/setup-tflint@v1
        with:
          versions: latest

      - name: Run TFLint
        run: |
          tflint --disable-rule=terraform_required_providers

      # - name: Upload Trivy results
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: trivy-results
      #     path: trivy-results.txt

      - name: Upload TFLint results to txt file
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: tflint-results
          path: tflint-results.txt
          
      - name: Check for typos
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: false
